name: familyone_flutter
description: FamilyOne Flutter app (skeleton)
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.2
  shared_preferences: ^2.3.2
  image_picker: ^1.1.2
  socket_io_client: ^2.0.3+1
  table_calendar: ^3.0.9
  file_picker: ^8.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^1.0.3
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
